name: Issue Triage

on:
  workflow_call:
    secrets:
      UPBOUND_BOT_GITHUB_TOKEN:
        description: 'A PAT with permissions that allow labeling and adding issues to a project'
        required: true      

jobs:
  debug:
    runs-on: ubuntu-22.04
    steps:
      - name: Debug
        run: |
          echo "github.event.issue.author_association: ${{ github.event.issue.author_association }}"
  community-issue-triage:
    if: ${{ (github.event.issue.author_association != 'OWNER' &&
      github.event.issue.author_association != 'MEMBER' &&
      github.event.issue.author_association != 'CONTRIBUTOR' &&
      github.event.issue.author_association != 'COLLABORATOR' ) }}
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    steps:
      - name: Label as community issue
        if: ${{ !contains(github.event.issue.labels.*.name, 'community') }}
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["community"]
            })
