name: Tag

on:
  workflow_call:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
        type: string
      message:
        description: 'Tag message'
        required: true
        type: string

jobs:
  create-tag:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Create Tag
        uses: negz/create-tag@39bae1e0932567a58c20dea5a1a0d18358503320 # v1
        with:
          version: ${{ inputs.version }}
          message: ${{ inputs.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
